module.exports = {
	SCHEMA: "SCHEMA",
	TABLE: "TABLE",
	COLUMN: "COLUMN",
	CONSTRAINT: "CONSTRAINT",
	INDEX: "INDEX",
	VIEW: "VIEW",
	MATERIALIZED_VIEW: "MATERIALIZED VIEW",
	FUNCTION: "FUNCTION",
	AGGREGATE: "AGGREGATE",
	SEQUENCE: "SEQUENCE",
	PROCEDURE: "PROCEDURE",
	TRIGGER: "TRIGGER",
};
