module.exports = {
	columns: {
		version: {
			nullable: false,
			datatype: "varchar",
			dataTypeCategory: "S",
			default: "",
			precision: 17,
			scale: null,
		},
		name: {
			nullable: false,
			datatype: "varchar",
			dataTypeCategory: "S",
			default: null,
			precision: null,
			scale: null,
		},
		status: {
			nullable: false,
			datatype: "varchar",
			dataTypeCategory: "S",
			default: "''",
			precision: 5,
			scale: null,
		},
		last_message: {
			nullable: true,
			datatype: "varchar",
			dataTypeCategory: "S",
			default: null,
			precision: null,
			scale: null,
		},
		script: {
			nullable: false,
			datatype: "varchar",
			dataTypeCategory: "S",
			default: "''",
			precision: null,
			scale: null,
		},
		applied_on: {
			nullable: true,
			datatype: "timestamp",
			dataTypeCategory: "D",
			default: null,
			precision: null,
			scale: null,
		},
	},
	constraints: {},
	// options: {
	//     withOids: false,
	// },
	indexes: {},
	privileges: {},
	owner: null,
};
